### ISSUE TITLE
Add Support for MSL-320M

### ISSUE THREAD

**Issue by forresthamilton** [donavanbecker/homebridge-meross-cloud#1]
I installed the Meross Cloud plugin but received the following message after homebridge started:

[12/31/2020, 5:06:52 PM] [Forrest Hamilton] A Meross Device has been discovered with Device Type: msl320m, which is currently not supported. Enable Device Discovery on Plugin Settings, Then Submit Meross Cloud Info Here: https://git.io/JLD51.

**Comment by donavanbecker** [comment]
@forresthamilton Did you enable device discovery and post the log?

**Comment by forresthamilton** [comment]
> @forresthamilton Did you enable device discovery and post the log?

I did enable device discovery which is how it discovered the LED light strip so in the mean time I’m using the Meross plugin and added the light strip under MSL120 (standard smart bulb).

**Comment by donavanbecker** [comment]
> > @forresthamilton Did you enable device discovery and post the log?
> 
> 
> 
> I did enable device discovery which is how it discovered the LED light strip so in the mean time I’m using the Meross plugin and added the light strip under MSL120 (standard smart bulb). 

Can you post the logs?

**Comment by forresthamilton** [comment]
Is this what you're looking for?

12/31/2020, 6:24:59 PM] [Forrest Hamilton] A Meross Device has been discovered with Device Type: msl320m, which is currently not supported. Enable Device Discovery on Plugin Settings, Then Submit Meross Cloud Info Here: https://git.io/JLD51.
status { category: 'PNConnectedCategory',
  operation: 'PNSubscribeOperation',
  affectedChannels: [ 'PlatformChannel#W7q7EA2O+LJCnDwMVc6cpo4a-w5JuoDw' ],
  subscribedChannels: [ 'PlatformChannel#W7q7EA2O+LJCnDwMVc6cpo4a-w5JuoDw' ],
  affectedChannelGroups: [],
  lastTimetoken: 0,
  currentTimetoken: '16094556324614283' }
Living Room TV
---------------------
11101200001 - Netflix
org.tizen.browser - Internet
3201903017953 - fuboTV
111299001912 - YouTube
3201807016597 - Apple TV
3201512006785 - Prime Video
3201901017640 - Disney+
3201601007625 - Hulu
3201708014618 - ESPN
3201710015067 - Universal Guide
3201908019041 - Apple Music
3201506003227 - STARZ
3201707014489 - YouTube TV
3201601007230 - HBO Max
3201710015037 - Gallery
3201601007250 - Google Play Movies ＆ TV
111012010001 - VUDU
3201710015016 - SmartThings
3201504001965 - Tubi - Free Movies ＆ TV
20192100001 - e-Manual
3201608010450 - HGTV
3201801015541 - Discovery GO
3201803015977 - TLC GO
3201803015978 - Investigation Discovery GO
3201809016951 - PBS Video
3201809016952 - PBS KIDS Video
3201902017822 - DisneyNOW
3201606009684 - Spotify - Music and Podcasts
3201608010313 - Food Network
3201803015979 - Animal Planet GO
3201803015980 - Science Channel GO
3201909019256 - MagellanTV Documentaries
3201909019271 - PrivacyChoices
3201811017337 - AMC
3202001019933 - Fitplan
3201909019241 - Calm
3202002020229 - Jillian Michaels Fitness App
3202002020129 - Echelon
3202001020081 - Barre3
11091000000 - Facebook Watch
[12/31/2020, 6:25:06 PM] [Nest] initing thermostat "Office Thermostat": deviceId: 09AA01AC181708G7 structureId: 0e4bfb40-0a66-11e4-b966-22000a6d8b12
[12/31/2020, 6:25:06 PM] [Nest] initing home_away_sensor "Home Occupied": deviceId: 0e4bfb40-0a66-11e4-b966-22000a6d8b12 structureId: 0e4bfb40-0a66-11e4-b966-22000a6d8b12
[12/31/2020, 6:25:06 PM] [Nest] initing temp_sensor (P) "Bedroom": deviceId: 18B430C2D0CC9DC8 structureId: 0e4bfb40-0a66-11e4-b966-22000a6d8b12
[12/31/2020, 6:25:13 PM] [DeebotEcovacs] INFO - stopping deebots discovery, number of deebots found : 1
[12/31/2020, 6:25:13 PM] [DeebotEcovacs] INFO - Discovered Deebot : Rosie
[12/31/2020, 6:25:13 PM] [DeebotEcovacs] INFO - Edge Cleaning for Rosie : true
[12/31/2020, 6:25:13 PM] [DeebotEcovacs] INFO - Spot Cleaning for Rosie : true
[12/31/2020, 6:25:13 PM] [DeebotEcovacs] INFO - SpotArea Cleaning for Rosie : false
[12/31/2020, 6:25:13 PM] [DeebotEcovacs] INFO - CustomArea Cleaning for Rosie : false
[12/31/2020, 6:33:27 PM] [Bunk Light] Failed to POST to the Meross Device MSL-120 at 192.168.0.97: { Error: socket hang up
    at createHangUpError (_http_client.js:330:17)
    at Socket.socketOnEnd (_http_client.js:431:23)
    at Socket.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17) code: 'ECONNRESET' }
[12/31/2020, 6:33:27 PM] [Bunk Light] Failed to POST to the Meross Device MSL-120 at 192.168.0.97: { Error: socket hang up
    at createHangUpError (_http_client.js:330:17)
    at Socket.socketOnEnd (_http_client.js:431:23)
    at Socket.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17) code: 'ECONNRESET' }
[12/31/2020, 6:33:27 PM] [Bunk Light] Failed to POST to the Meross Device MSL-120 at 192.168.0.97: { Error: socket hang up
    at createHangUpError (_http_client.js:330:17)
    at Socket.socketOnEnd (_http_client.js:431:23)
    at Socket.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17) code: 'ECONNRESET' }
[12/31/2020, 6:33:30 PM] [Bunk Light] MSL-120 turned Off
[12/31/2020, 6:40:04 PM] [Homebridge UI] Terminal session ended.
[12/31/2020, 6:40:07 PM] [Homebridge UI] Starting terminal session
[12/31/2020, 6:41:30 PM] [Homebridge UI] Terminal session ended.
[12/31/2020, 6:41:34 PM] [Homebridge UI] Starting terminal session
[12/31/2020, 6:44:02 PM] [Bunk Light] Failed to POST to the Meross Device MSL-120 at 192.168.0.97: { Error: socket hang up
    at createHangUpError (_http_client.js:330:17)
    at Socket.socketOnEnd (_http_client.js:431:23)
    at Socket.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17) code: 'ECONNRESET' }
[12/31/2020, 6:44:02 PM] [Bunk Light] Failed to POST to the Meross Device MSL-120 at 192.168.0.97: { Error: socket hang up
    at createHangUpError (_http_client.js:330:17)
    at Socket.socketOnEnd (_http_client.js:431:23)
    at Socket.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17) code: 'ECONNRESET' }
[12/31/2020, 6:44:02 PM] [Bunk Light] Failed to POST to the Meross Device MSL-120 at 192.168.0.97: { Error: socket hang up
    at createHangUpError (_http_client.js:330:17)
    at Socket.socketOnEnd (_http_client.js:431:23)
    at Socket.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17) code: 'ECONNRESET' }
[12/31/2020, 6:44:56 PM] [Vivint] Renewed Vivint API session.  s=5742ab4d-8a0f-4ff8-b7bc-7524b657d677 s=e1aa3d8e-6c6c-4386-a264-2e6658a6add0
[12/31/2020, 6:44:57 PM] [Vivint] Handling incoming device snapshot for timestamp 2020-12-31T23:41:19.418000
[12/31/2020, 6:45:22 PM] [Vivint] received pubNub msg
[12/31/2020, 6:45:22 PM] [Vivint] {"_id":"1526970477457091|1","da":{"d":[{"_id":37,"act":"wireless_sensor","s":true}],"plctx":{"context_carrier":{"previous_handler":"Subscriber Update Handler","tracing_context":{"uber-trace-id":"4f8db6d70497cf9:4f8db6d70497cf9:0:0"}},"mid":"5fee6292c2e1c90001c19e95","ts":"2020-12-31T23:45:22.676"}},"op":"u","panid":1526970477457091,"parid":1,"t":"account_partition"}
[12/31/2020, 6:45:27 PM] [Vivint] received pubNub msg
[12/31/2020, 6:45:27 PM] [Vivint] {"_id":"1526970477457091|1","da":{"d":[{"_id":37,"act":"wireless_sensor","s":false}],"plctx":{"context_carrier":{"previous_handler":"Subscriber Update Handler","tracing_context":{"uber-trace-id":"6cf31f90bb3cb095:6cf31f90bb3cb095:0:0"}},"mid":"5fee6297f411be0001a26ffa","ts":"2020-12-31T23:45:27.295"}},"op":"u","panid":1526970477457091,"parid":1,"t":"account_partition"}
[12/31/2020, 6:45:39 PM] [Bunk Light] MSL-120 turned On
[12/31/2020, 6:55:08 PM] [Homebridge UI] Terminal session ended.
[12/31/2020, 6:55:09 PM] [Homebridge UI] Homebridge restart request received
[12/31/2020, 6:55:09 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[12/31/2020, 6:55:09 PM] [HB Supervisor] Sending SIGTERM to Homebridge
[12/31/2020, 6:55:09 PM] Got SIGTERM, shutting down Homebridge...
[12/31/2020, 6:55:09 PM] [DeebotEcovacs] INFO - shutdown
[12/31/2020, 6:55:15 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[12/31/2020, 6:55:20 PM] [HB Supervisor] Restarting Homebridge...
[12/31/2020, 6:55:20 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[12/31/2020, 6:55:20 PM] [HB Supervisor] Started Homebridge v1.2.5 with PID: 26527
[12/31/2020, 6:55:26 PM] Loaded config.json with 2 accessories and 7 platforms.
[12/31/2020, 6:55:27 PM] ---
/usr/local/lib/node_modules/npm/lib/config/defaults.js:76
var temp = osenv.tmpdir()
                 ^

TypeError: osenv.tmpdir is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/defaults.js:76:18)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)

**Comment by donavanbecker** [comment]
> Is this what you're looking for?

None of this has info from the meross cloud plugin. the metros cloud plugin would be logs that start with `[MerossCloud]`.

**Comment by forresthamilton** [comment]
I'm not showing any of those in the logs. All I have regarding Meross is:
[Forrest Hamilton] {"uuid":"2007299813799690822348e1e9270dfa","onlineStatus":1,"devName":"Bunk Light","devIconId":"device021_un","bindTime":1607794539,"deviceType":"msl320m","subType":"un","channels":[{}],"region":"us","fmwareVersion":"2.1.2","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"skillNumber":"","domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us-alter.meross.com"}
[1/1/2021, 12:59:37 PM] [Forrest Hamilton] {"_events":{},"_eventsCount":6,"clientResponseTopic":null,"waitingMessageIds":{},"token":"e5ad6656a18a4ffb17e285080c71d6b12e8040f283147a01f0c378923388fa08","key":"b74b167b116198e15e87442d04db12c0","userId":"1001718","dev":{"uuid":"2007299813799690822348e1e9270dfa","onlineStatus":1,"devName":"Bunk Light","devIconId":"device021_un","bindTime":1607794539,"deviceType":"msl320m","subType":"un","channels":[{}],"region":"us","fmwareVersion":"2.1.2","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"skillNumber":"","domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us-alter.meross.com"}}
status {
  category: 'PNConnectedCategory',
  operation: 'PNSubscribeOperation',
  affectedChannels: [ 'PlatformChannel#W7q7EA2O+LJCnDwMVc6cpo4a-w5JuoDw' ],
  subscribedChannels: [ 'PlatformChannel#W7q7EA2O+LJCnDwMVc6cpo4a-w5JuoDw' ],
  affectedChannelGroups: [],
  lastTimetoken: 0,
  currentTimetoken: '16095236283900991'
}
[1/1/2021, 12:59:49 PM] [Forrest Hamilton] A Meross Device has been discovered with Device Type: msl320m, which is currently not supported. Enable Device Discovery on Plugin Settings, Then Submit Meross Cloud Info Here: https://git.io/JLD51.

**Comment by forresthamilton** [comment]
It seems that is because I changed the name to Forrest Hamilton from MerossCloud.

**Comment by donavanbecker** [comment]
> It seems that is because I changed the name to Forrest Hamilton from MerossCloud.

Makes sense, but last log didn't have what you just posted. Thanks.

**Comment by forresthamilton** [comment]
I have purchased another Meross product to help you to add devices to this plugin. Do you want me to post here or create another thread?

**Comment by forresthamilton** [comment]
Considering my other support request was closed by a bot, I will post the logs here. Requesting adding support for MOD-100 Smart Oil Diffuser

[Forrest Hamilton] {"uuid":"2008288134558490827648e1e92f0927","onlineStatus":1,"devName":"Smart Essential Oil Diffuser","devIconId":"device_mod100_un","bindTime":1609806234,"deviceType":"mod100","subType":"un","channels":[{}],"region":"us","fmwareVersion":"3.1.5","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"skillNumber":"","domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us-alter.meross.com"}
[1/4/2021, 7:32:42 PM] [Forrest Hamilton] {"_events":{},"_eventsCount":6,"clientResponseTopic":null,"waitingMessageIds":{},"token":"e5ad6656a18a4ffb17e285080c71d6b189b3ec8e60d6b5961994b9011cf553f4","key":"b74b167b116198e15e87442d04db12c0","userId":"1001718","dev":{"uuid":"2008288134558490827648e1e92f0927","onlineStatus":1,"devName":"Smart Essential Oil Diffuser","devIconId":"device_mod100_un","bindTime":1609806234,"deviceType":"mod100","subType":"un","channels":[{}],"region":"us","fmwareVersion":"3.1.5","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"skillNumber":"","domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us-alter.meross.com"}}

**Comment by donavanbecker** [comment]
@forresthamilton not sure if you have saw or not, I was able to publish version 1.0.1. This version only supports mss110 right now but I would like to get this Meross device supported also. I have changed the device discovery up a little and was wondering if you could install the latest version of homebridge-meross-cloud? login and turn on devicediscovery?

then you would reboot homebridge and grab the new logs that will be outputted from this device discovery and paste them here so I can see what kind of command I can send to this device. Thanks!

**Comment by forresthamilton** [comment]
> @forresthamilton not sure if you have saw or not, I was able to publish version 1.0.1. This version only supports mss110 right now but I would like to get this Meross device supported also. I have changed the device discovery up a little and was wondering if you could install the latest version of homebridge-meross-cloud? login and turn on devicediscovery?
> 
> then you would reboot homebridge and grab the new logs that will be outputted from this device discovery and paste them here so I can see what kind of command I can send to this device. Thanks!

Sorry for the delayed response. Here are the logs:
[2/26/2021, 11:40:30 AM] [Forrest Hamilton] A Meross Device has been discovered with Device Type: mod100, which is currently not supported. Enable Device Discovery on Plugin Settings, Then Submit Meross Cloud Info Here: https://git.io/JLD51.
[2/26/2021, 11:40:30 AM] [Forrest Hamilton] A Meross Device has been discovered with Device Type: msl320m, which is currently not supported. Enable Device Discovery on Plugin Settings, Then Submit Meross Cloud Info Here: https://git.io/JLD51.
[2/26/2021, 11:40:10 AM] [Forrest Hamilton] {"uuid":"2008288134558490827648e1e92f0927","onlineStatus":1,"devName":"Smart Essential Oil Diffuser","devIconId":"device_mod100_un","bindTime":1609806234,"deviceType":"mod100","subType":"un","channels":[{}],"region":"us","fmwareVersion":"3.1.5","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"skillNumber":"","domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us-alter.meross.com"}
[2/26/2021, 11:40:10 AM] [Forrest Hamilton] {"_events":{},"_eventsCount":6,"clientResponseTopic":null,"waitingMessageIds":{},"token":"e5ad6656a18a4ffb17e285080c71d6b16d172b2431a9ce03f6e8e71ab7a92851","key":"b74b167b116198e15e87442d04db12c0","userId":"1001718","dev":{"uuid":"2008288134558490827648e1e92f0927","onlineStatus":1,"devName":"Smart Essential Oil Diffuser","devIconId":"device_mod100_un","bindTime":1609806234,"deviceType":"mod100","subType":"un","channels":[{}],"region":"us","fmwareVersion":"3.1.5","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"skillNumber":"","domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us-alter.meross.com"}}
[2/26/2021, 11:40:13 AM] [Forrest Hamilton] {"uuid":"2007299813799690822348e1e9270dfa","onlineStatus":1,"devName":"Bunk Light","devIconId":"device021_un","bindTime":1607794539,"deviceType":"msl320m","subType":"un","channels":[{}],"region":"us","fmwareVersion":"2.1.2","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"skillNumber":"","domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us-alter.meross.com"}
[2/26/2021, 11:40:13 AM] [Forrest Hamilton] {"_events":{},"_eventsCount":6,"clientResponseTopic":null,"waitingMessageIds":{},"token":"e5ad6656a18a4ffb17e285080c71d6b16d172b2431a9ce03f6e8e71ab7a92851","key":"b74b167b116198e15e87442d04db12c0","userId":"1001718","dev":{"uuid":"2007299813799690822348e1e9270dfa","onlineStatus":1,"devName":"Bunk Light","devIconId":"device021_un","bindTime":1607794539,"deviceType":"msl320m","subType":"un","channels":[{}],"region":"us","fmwareVersion":"2.1.2","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"skillNumber":"","domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us-alter.meross.com"}}

**Comment by forresthamilton** [comment]
Let me know if this isn't everything that you're looking for.

**Comment by donavanbecker** [comment]
No. Did you update to the latest version of the plugin?

**Comment by forresthamilton** [comment]
Yes. Let me restart homebridge again and see what the logs say.

**Comment by forresthamilton** [comment]
2/26/2021, 6:08:23 PM] [Meross Cloud] Device Type: mod100, is currently not supported. Submit Feature Requests Here: https://git.io/JtfVC
[2/26/2021, 6:08:23 PM] [Meross Cloud] Device Type: msl320m, is currently not supported. Submit Feature Requests Here: https://git.io/JtfVC
[2/26/2021, 6:08:24 PM] [Meross Cloud] All-Data: {"all":{"system":{"hardware":{"type":"mod100","subType":"un","version":"3.0.0","chipType":"mt7682","uuid":"2008288134558490827648e1e92f0927","macAddress":"48:e1:e9:2f:09:27"},"firmware":{"version":"3.1.5","compileTime":"2020/09/01 17:03:31 GMT +08:00","wifiMac":"e8:8d:28:5f:da:31","innerIp":"192.168.0.100","server":"mqtt.meross.com","port":443,"userId":1001718},"time":{"timestamp":1614380903,"timezone":"America/New_York","timeRule":[[1604210400,-18000,0],[1615705200,-14400,1],[1636264800,-18000,0],[1647154800,-14400,1],[1667714400,-18000,0],[1678604400,-14400,1],[1699164000,-18000,0],[1710054000,-14400,1],[1730613600,-18000,0],[1741503600,-14400,1],[1762063200,-18000,0],[1772953200,-14400,1],[1793512800,-18000,0],[1805007600,-14400,1],[1825567200,-18000,0],[1836457200,-14400,1],[1857016800,-18000,0],[1867906800,-14400,1],[1888466400,-18000,0],[1899356400,-14400,1]]},"online":{"status":1}},"digest":{"triggerx":[],"timerx":[],"diffuser":{"type":"mod100","light":[{"channel":0,"onoff":0,"lmTime":1610476045,"mode":0,"luminance":100,"rgb":65313}],"spray":[{"channel":0,"mode":2,"lmTime":1614363138}]}}}}
[2/26/2021, 6:08:24 PM] [Meross Cloud] All-Data: {"all":{"system":{"hardware":{"type":"msl320m","subType":"un","version":"2.0.0","chipType":"mt7682","uuid":"2007299813799690822348e1e9270dfa","macAddress":"48:e1:e9:27:0d:fa"},"firmware":{"version":"2.1.2","compileTime":"2020/07/07 16:11:46 GMT +08:00","wifiMac":"e8:8d:28:5f:da:31","innerIp":"192.168.0.97","server":"mqtt.meross.com","port":443,"userId":1001718},"time":{"timestamp":1614380903,"timezone":"America/New_York","timeRule":[[1604210400,-18000,0],[1615705200,-14400,1],[1636264800,-18000,0],[1647154800,-14400,1],[1667714400,-18000,0],[1678604400,-14400,1],[1699164000,-18000,0],[1710054000,-14400,1],[1730613600,-18000,0],[1741503600,-14400,1],[1762063200,-18000,0],[1772953200,-14400,1],[1793512800,-18000,0],[1805007600,-14400,1],[1825567200,-18000,0],[1836457200,-14400,1],[1857016800,-18000,0],[1867906800,-14400,1],[1888466400,-18000,0],[1899356400,-14400,1]]},"online":{"status":1}},"digest":{"togglex":[{"channel":0,"onoff":0,"lmTime":1614369905}],"triggerx":[],"timerx":[],"light":{"capacity":5,"channel":0,"rgb":255,"temperature":0,"luminance":2,"transform":-1}}}}

**Comment by forresthamilton** [comment]
Is that it?

**Comment by donavanbecker** [comment]
Yes
