### ISSUE TITLE
Add support for HP110A

### ISSUE THREAD

**Issue by VinceRedmount** [donavanbecker/homebridge-meross-cloud#20]
**Describe The Bug:**

Support for Cherub Baby Machine HP110A

**To Reproduce:**

[MerossCloud] A Meross Device has been discovered with Device Type: hp110a, which is currently not supported. Enable Device Discovery on Plugin Settings, Then Submit Meross Cloud Info Here: https://git.io/JLD51.

**Logs:**

[03/02/2021, 16:48:29] [MerossCloud] {"_events":{},"_eventsCount":6,"clientResponseTopic":null,"waitingMessageIds":{},"token":"d5ed8e85bcb9ec0ef5dcd37d611c13b94241b5bb872406b262a0518cae5bfd3a","key":"d1a9af0932ee84a5115b79c41c08ca0f","userId":"861827","dev":{"uuid":"2003246861054090809448e1e9191b44","onlineStatus":1,"devName":"Cherub Baby Machine","devIconId":"device054_un","bindTime":1611741045,"deviceType":"hp110a","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.1.22","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu-alter.meross.com"}}

**Homebridge Config:**

 "name": "MerossCloud",
            "email": "XXXXXXXXX",
            "password": "XXXXXXX",
            "devicediscovery": true,
            "platform": "MerossCloud"

**Environment:**

- **Node.js Version**:v14.15.4
- **NPM Version**: v6.14.10
- **Homebridge Version**: 1.1.7
- **Homebridge Meross Cloud Plugin Version**: homebridge-meross-cloud v0.1.1-beta.0
- **Homebridge Config UI X Plugin Version**:homebridge-config-ui-x v4.37.0
- **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by donavanbecker** [comment]
@VinceRedmount  not sure if you have saw or not, I was able to publish version 1.0.1. This version only supports mss110 right now but I would like to get this Meross device supported also. I have changed the device discovery up a little and was wondering if you could install the latest version of homebridge-meross-cloud? login and turn on devicediscovery?

then you would reboot homebridge and grab the new logs that will be outputted from this device discovery and paste them here so I can see what kind of command I can send to this device. Thanks!

**Comment by VinceRedmount** [comment]
[26/02/2021, 16:05:14] [MerossCloud] All-Data: {"all":{"system":{"hardware":{"type":"hp110a","subType":"us","version":"4.0.0","chipType":"MT7686","uuid":"2003246861054090809448e1e9191b44","macAddress":"48:e1:e9:19:1b:44"},"firmware":{"version":"4.1.22","compileTime":"Mar 18 2020 09:19:57","mcu":{"productId":"5adbusgachewfheh","version":"1.5.3","type":"hp110a_mcu"},"wifiMac":"48:dd:0c:ba:ae:05","innerIp":"192.168.4.59","server":"mqtt.meross.com","port":443,"userId":XXXXXX},"time":{"timestamp":1614351914,"timezone":"Europe/Paris","timeRule":[[1603587600,3600,0],[1616893200,7200,1],[1635642000,3600,0],[1648342800,7200,1],[1667091600,3600,0],[1679792400,7200,1],[1698541200,3600,0],[1711846800,7200,1],[1729990800,3600,0],[1743296400,7200,1],[1761440400,3600,0],[1774746000,7200,1],[1792890000,3600,0],[1806195600,7200,1],[1824944400,3600,0],[1837645200,7200,1],[1856394000,3600,0],[1869094800,7200,1],[1887843600,3600,0],[1901149200,7200,1]]},"online":{"status":1}},"digest":{"togglex":[{"channel":0,"onoff":0,"lmTime":1614280397}],"triggerx":[],"timerx":[],"light":{"channel":0,"capacity":5,"luminance":1,"temperature":50,"rgb":196864,"effect":4}}}}


Not sure if safe to post userId
Thanks for your time

**Comment by donavanbecker** [comment]
@VinceRedmount Okay I pushed out a beta, with me not having the device and being able to actually communicate with it and seeing the logs. I will need your help.

if you can install the latest beta:

Beta: `1.0.2-beta.1`

It is displaying as a Light, not sure what else you would like me to display it as?
Also when I can figure out how to control other things, I can potentially add other sensors to this.

**Comment by VinceRedmount** [comment]
Just installed the beta. The plugin has been shut down by HB.

Please see below logs
[26/02/2021, 17:17:45] [MerossCloud] System-Abilities: {"payloadVersion":1,"ability":{"Appliance.Config.Key":{},"Appliance.Config.WifiList":{},"Appliance.Config.Wifi":{},"Appliance.Config.Trace":{},"Appliance.System.All":{},"Appliance.System.Hardware":{},"Appliance.System.Firmware":{},"Appliance.System.Debug":{},"Appliance.System.Online":{},"Appliance.System.Time":{},"Appliance.System.Ability":{},"Appliance.System.Runtime":{},"Appliance.System.Report":{},"Appliance.System.Position":{},"Appliance.Control.Multiple":{"maxCmdNum":5},"Appliance.Control.ToggleX":{},"Appliance.Control.TimerX":{"sunOffsetSupport":1},"Appliance.Control.TriggerX":{},"Appliance.Control.Bind":{},"Appliance.Control.Unbind":{},"Appliance.Control.Upgrade":{},"Appliance.Control.Light":{"capacity":15},"Appliance.Control.Mp3":{},"Appliance.Mcu.Hp110.Firmware":{},"Appliance.Mcu.Hp110.Favorite":{},"Appliance.Mcu.Hp110.Preview":{},"Appliance.Mcu.Hp110.Lock":{},"Appliance.Mcu.Upgrade":{},"Appliance.Digest.TriggerX":{},"Appliance.Digest.TimerX":{}}}
[26/02/2021, 17:17:45] TypeError: this.devicestatus.all.digest.light is not iterable
    at Object.callback (/usr/local/lib/node_modules/homebridge-meross-cloud/src/devices/hp110a.ts:132:56)
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/meross-cloud/index.js:281:66)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/mqtt/lib/client.js:410:12)
    at work (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/readable-stream/lib/_stream_writable.js:307:11)

**Comment by donavanbecker** [comment]
I kind of thought this would happen. let me publish a change and we can try again.

**Comment by donavanbecker** [comment]
okay new beta out!

Beta: `1.0.2-beta.4`

**Comment by VinceRedmount** [comment]
The device is discovered and in Apple Home ! As of now, I can turn it on without issue. Turning it off does not work (off for a second and back on). The device is capable of displaying colours and different whites and is dimmable (like a philips hue white and color bulb). I do not know if it is doable to display it this way.

Logs below :
[26/02/2021, 17:37:33] [MerossCloud] System-Abilities: {"payloadVersion":1,"ability":{"Appliance.Config.Key":{},"Appliance.Config.WifiList":{},"Appliance.Config.Wifi":{},"Appliance.Config.Trace":{},"Appliance.System.All":{},"Appliance.System.Hardware":{},"Appliance.System.Firmware":{},"Appliance.System.Debug":{},"Appliance.System.Online":{},"Appliance.System.Time":{},"Appliance.System.Ability":{},"Appliance.System.Runtime":{},"Appliance.System.Report":{},"Appliance.System.Position":{},"Appliance.Control.Multiple":{"maxCmdNum":5},"Appliance.Control.ToggleX":{},"Appliance.Control.TimerX":{"sunOffsetSupport":1},"Appliance.Control.TriggerX":{},"Appliance.Control.Bind":{},"Appliance.Control.Unbind":{},"Appliance.Control.Upgrade":{},"Appliance.Control.Light":{"capacity":15},"Appliance.Control.Mp3":{},"Appliance.Mcu.Hp110.Firmware":{},"Appliance.Mcu.Hp110.Favorite":{},"Appliance.Mcu.Hp110.Preview":{},"Appliance.Mcu.Hp110.Lock":{},"Appliance.Mcu.Upgrade":{},"Appliance.Digest.TriggerX":{},"Appliance.Digest.TimerX":{}}}

**Comment by donavanbecker** [comment]
v1.1.0 is released pleas try and let me know if the on and off are working correctly.

**Comment by VinceRedmount** [comment]
@donavanbecker ON/OFF work correctly. Thanks
