### ISSUE TITLE
v1.0.0 Device Discovery causes reboot loop

### ISSUE THREAD

**Issue by gileswells** [donavanbecker/homebridge-meross-cloud#32]
**Describe The Bug:**

After upgrading to v1.0.0 with 12 MSS110-2 plugs homebridge would endlessly cycle and reboot.

**To Reproduce:**

Run v1.0.0 with Device Discovery enabled in settings.

**Expected behavior:**

Homebridge boots up as normal and device discovery happens and logs what it finds during startup.

**Logs:**

```
[2/25/2021, 11:42:05 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[2/25/2021, 11:42:10 PM] [HB Supervisor] Restarting Homebridge...
[2/25/2021, 11:42:10 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[2/25/2021, 11:42:10 PM] [HB Supervisor] Started Homebridge v1.3.1 with PID: 32064
Initializing HAP-NodeJS v0.9.2...
[2/25/2021, 11:42:11 PM] Loaded config.json with 1 accessories and 5 platforms.
[2/25/2021, 11:42:11 PM] Loaded 14 cached accessories from cachedAccessories.
[2/25/2021, 11:42:11 PM] ---
[2/25/2021, 11:42:11 PM] Loaded plugin: homebridge-config-ui-x@4.39.1
[2/25/2021, 11:42:11 PM] Registering platform 'homebridge-config-ui-x.config'
[2/25/2021, 11:42:11 PM] ---
[2/25/2021, 11:42:11 PM] Loaded plugin: homebridge-http-ping@0.2.2
[2/25/2021, 11:42:11 PM] Registering accessory 'homebridge-http-ping.http-ping'
[2/25/2021, 11:42:11 PM] ---
[2/25/2021, 11:42:12 PM] Loaded plugin: homebridge-meross@3.5.0
[2/25/2021, 11:42:12 PM] Registering accessory 'homebridge-meross.Meross'
[2/25/2021, 11:42:12 PM] ---
[2/25/2021, 11:42:12 PM] Loaded plugin: homebridge-meross-cloud@1.0.0
[2/25/2021, 11:42:12 PM] Registering platform 'homebridge-meross-cloud.MerossCloud'
[2/25/2021, 11:42:12 PM] ---
[2/25/2021, 11:42:12 PM] Loaded plugin: homebridge-roku@3.0.1
[2/25/2021, 11:42:12 PM] Registering accessory 'homebridge-roku.Roku'
[2/25/2021, 11:42:12 PM] ---
[2/25/2021, 11:42:12 PM] Loaded plugin: homebridge-vesync-v2@2.0.1
[2/25/2021, 11:42:12 PM] Plugin 'homebridge-vesync-v2' tried to register with an incorrect plugin identifier: 'homebridge-vesync'. Please report this to the developer!
[2/25/2021, 11:42:12 PM] Registering platform 'homebridge-vesync-v2.VesyncPlug'
[2/25/2021, 11:42:12 PM] ---
[2/25/2021, 11:42:12 PM] Loaded plugin: homebridge-weather-plus@3.2.5
[2/25/2021, 11:42:13 PM] Registering platform 'homebridge-weather-plus.WeatherPlus'
[2/25/2021, 11:42:13 PM] ---
[2/25/2021, 11:42:13 PM] Loaded plugin: homebridge-wol@4.3.0
[2/25/2021, 11:42:13 PM] Registering accessory 'homebridge-wol.NetworkDevice'
[2/25/2021, 11:42:13 PM] ---
[2/25/2021, 11:42:13 PM] Loading 5 platforms...
[2/25/2021, 11:42:13 PM] [Config] Initializing config platform...
[2/25/2021, 11:42:13 PM] [Config] Running in Service Mode
[2/25/2021, 11:42:13 PM] [VesyncPlug] Initializing VesyncPlug platform...
[2/25/2021, 11:42:13 PM] [MerossCloud] Initializing MerossCloud platform...
[2/25/2021, 11:42:13 PM] [MerossCloud] Finished initializing platform: MerossCloud
[2/25/2021, 11:42:13 PM] [MerossCloud] Using Default Refresh Rate.
[2/25/2021, 11:42:13 PM] [MerossCloud] Config OK
[2/25/2021, 11:42:13 PM] Loading 1 accessories...
[2/25/2021, 11:42:13 PM] [Meeting Bulb] Initializing Meross accessory...
[2/25/2021, 11:42:13 PM] [MerossCloud] Loading accessory from cache: Dust Bunny mss110
[2/25/2021, 11:42:13 PM] [MerossCloud] Loading accessory from cache: Unicorn Sparkle mss110
[2/25/2021, 11:42:13 PM] [MerossCloud] Loading accessory from cache: Mr Robot mss110
[2/25/2021, 11:42:13 PM] [MerossCloud] Loading accessory from cache: Hockey Puck mss110
[2/25/2021, 11:42:13 PM] [MerossCloud] Loading accessory from cache: Hurricane mss110
[2/25/2021, 11:42:13 PM] [MerossCloud] Loading accessory from cache: Breeze mss110
[2/25/2021, 11:42:13 PM] [MerossCloud] Loading accessory from cache: Wind mss110
[2/25/2021, 11:42:13 PM] [MerossCloud] Loading accessory from cache: Sebastian mss110
[2/25/2021, 11:42:13 PM] [MerossCloud] Loading accessory from cache: Chandelure mss110
[2/25/2021, 11:42:13 PM] [MerossCloud] Loading accessory from cache: Christmas Tree mss110
[2/25/2021, 11:42:13 PM] [MerossCloud] Loading accessory from cache: Lightning mss110
[2/25/2021, 11:42:13 PM] [MerossCloud] Loading accessory from cache: PS4 mss110
[2/25/2021, 11:42:13 PM] [MerossCloud] Executed didFinishLaunching callback
Preparing Advertiser for 'Mac Mini Homebridge 9AC9' using ciao backend!
Setup Payload:
X-HM://*************
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ ###-##-### │     
    └────────────┘     
                       
Starting to advertise 'Mac Mini Homebridge 9AC9' using ciao backend!
[2/25/2021, 11:42:13 PM] Homebridge v1.3.1 (Mac Mini Homebridge) is running on port 51602.
Initializing HAP-NodeJS v0.9.2...
Initializing HAP-NodeJS v0.9.2...
[2/25/2021, 11:42:13 PM] [homebridge-weather-plus] Launched external bridge with PID 32070
[2/25/2021, 11:42:13 PM] [Meeting Bulb] Launched external bridge with PID 32071
[2/25/2021, 11:42:13 PM] [MerossCloud] New device 2008278425567190827048e1e92e5c49: {"uuid":"2008278425567190827048e1e92e5c49","onlineStatus":1,"devName":"Meeting Bulb","devIconId":"device036","bindTime":1610989756,"deviceType":"msl120d","subType":"us","channels":[{}],"region":"us","fmwareVersion":"2.1.4","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"skillNumber":"","domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us-alter.meross.com"}
[2/25/2021, 11:42:13 PM] TypeError: Cannot read property 'publish' of undefined
    at MerossCloudDevice.publishMessage (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/meross-cloud/index.js:327:21)
    at MerossCloudDevice.getSystemAllData (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/meross-cloud/index.js:348:21)
    at MerossCloudPlatform.deviceInfo (/usr/local/lib/node_modules/homebridge-meross-cloud/src/platform.ts:178:14)
    at MerossCloud.<anonymous> (/usr/local/lib/node_modules/homebridge-meross-cloud/src/platform.ts:97:12)
    at MerossCloud.emit (node:events:378:20)
    at MerossCloud.connectDevice (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/meross-cloud/index.js:127:14)
    at /usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/meross-cloud/index.js:170:34
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/meross-cloud/index.js:160:32
    at Request._callback (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/meross-cloud/index.js:97:40)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/request/request.js:185:22)
    at Request.emit (node:events:378:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:378:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-meross-cloud/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:484:28)
[2/25/2021, 11:42:13 PM] Got SIGTERM, shutting down Homebridge...
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Mac Mini Homebridge",
        "pin": "***-**-***",
        "username": "[USERNAME]",
        "port": 51602,
        "advertiser": "ciao"
    },
    "platforms": [
        {
            "auth": "form",
            "platform": "config",
            "tempUnits": "f",
            "theme": "auto",
            "lang": "auto",
            "name": "Config",
            "port": 8581
        },
        {
            "name": "VesyncPlug",
            "username": "[EMAIL ADDRESS]",
            "password": "[PASSWORD]",
            "platform": "VesyncPlug"
        },
        {
            "name": "MerossCloud",
            "email": "[EMAIL ADDRESS]",
            "password": "[PASSWORD]",
            "devicediscovery": true,
            "platform": "MerossCloud"
        },
        {
            "units": "us",
            "interval": 5,
            "stations": [
                {
                    "service": "openweathermap",
                    "key": "[API KEY]",
                    "locationGeo": [
                        28.55478475,
                        -81.16407629
                    ],
                    "locationCity": "[CITY, STATE]",
                    "language": "en",
                    "compatibility": "home",
                    "conditionCategory": "simple",
                    "now": true,
                    "extraHumidity": false,
                    "hidden": [
                        "Cloud Cover",
                        "Condition",
                        "Condition Category",
                        "Current Relative Humidity",
                        "Dew Point",
                        "Forecast Day",
                        "Humidity",
                        "Observation Station",
                        "Observation Time",
                        "Ozone",
                        "Rain 1h",
                        "Rain Day",
                        "Rain Chance",
                        "Snow",
                        "Solar Radiation",
                        "Temperature Min",
                        "Temperature Apparent",
                        "UV Index",
                        "Visibility",
                        "Wind Direction",
                        "Wind Speed Max"
                    ]
                }
            ],
            "_bridge": {
                "username": "[USERNAME]",
                "port": 44142
            },
            "platform": "WeatherPlus"
        }
    ],
    "accessories": [
        {
            "accessory": "Meross",
            "model": "MSL-120",
            "firmwareRevision": "2.1.4",
            "deviceUrl": "192.168.1.123",
            "name": "Meeting Bulb",
            "timestamp": 1611773257,
            "messageId": "[MESSAGE ID]",
            "channel": 0,
            "sign": "[SIGN HASH]",
            "_bridge": {
                "username": "[USERNAME]",
                "port": 55624
            }
        }
    ]
}
```

**Screenshots:**

# **Environment:**

- **Node.js Version**: v15.10.0
- **NPM Version**: 7.5.6
- **Homebridge Version**: 1.3.1
- **Homebridge Meross Cloud Plugin Version**: 1.0.0
- **Homebridge Config UI X Plugin Version**: v4.39.1
- **Operating System**: macOS

**Comment by donavanbecker** [comment]
Fix with v1.0.1
